//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 04:51:18 PM IST 
//


package xmlParser;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subnetSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="subnetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="availableIpAddressCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="vpcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cidrBlock" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "subnetSet"
})
@XmlRootElement(name = "DescribeSubnetsResponse")
public class DescribeSubnetsResponse {

    @XmlElement(required = true)
    protected String requestId;
    @XmlElement(required = true)
    protected DescribeSubnetsResponse.SubnetSet subnetSet;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the subnetSet property.
     * 
     * @return
     *     possible object is
     *     {@link DescribeSubnetsResponse.SubnetSet }
     *     
     */
    public DescribeSubnetsResponse.SubnetSet getSubnetSet() {
        return subnetSet;
    }

    /**
     * Sets the value of the subnetSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescribeSubnetsResponse.SubnetSet }
     *     
     */
    public void setSubnetSet(DescribeSubnetsResponse.SubnetSet value) {
        this.subnetSet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="subnetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="availableIpAddressCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="vpcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cidrBlock" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class SubnetSet {

        @XmlElement(nillable = true)
        protected List<DescribeSubnetsResponse.SubnetSet.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescribeSubnetsResponse.SubnetSet.Item }
         * 
         * 
         */
        public List<DescribeSubnetsResponse.SubnetSet.Item> getItem() {
            if (item == null) {
                item = new ArrayList<DescribeSubnetsResponse.SubnetSet.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="subnetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="availableIpAddressCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="vpcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cidrBlock" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subnetId",
            "availableIpAddressCount",
            "vpcId",
            "cidrBlock"
        })
        public static class Item {

            @XmlElement(required = true)
            protected String subnetId;
            protected int availableIpAddressCount;
            @XmlElement(required = true)
            protected String vpcId;
            @XmlElement(required = true)
            protected String cidrBlock;

            /**
             * Gets the value of the subnetId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubnetId() {
                return subnetId;
            }

            /**
             * Sets the value of the subnetId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubnetId(String value) {
                this.subnetId = value;
            }

            /**
             * Gets the value of the availableIpAddressCount property.
             * 
             */
            public int getAvailableIpAddressCount() {
                return availableIpAddressCount;
            }

            /**
             * Sets the value of the availableIpAddressCount property.
             * 
             */
            public void setAvailableIpAddressCount(int value) {
                this.availableIpAddressCount = value;
            }

            /**
             * Gets the value of the vpcId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVpcId() {
                return vpcId;
            }

            /**
             * Sets the value of the vpcId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVpcId(String value) {
                this.vpcId = value;
            }

            /**
             * Gets the value of the cidrBlock property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCidrBlock() {
                return cidrBlock;
            }

            /**
             * Sets the value of the cidrBlock property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCidrBlock(String value) {
                this.cidrBlock = value;
            }

        }

    }

}
