//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 04:51:18 PM IST 
//


package xmlParser;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fromPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="toPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ipProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element ref="{http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/}ipRanges"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "IpPermissionsEgress")
public class IpPermissionsEgress {

    @XmlElement(nillable = true)
    protected List<IpPermissionsEgress.IpPermissionEgressItem> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpPermissionsEgress.IpPermissionEgressItem }
     * 
     * 
     */
    public List<IpPermissionsEgress.IpPermissionEgressItem> getItem() {
        if (item == null) {
            item = new ArrayList<IpPermissionsEgress.IpPermissionEgressItem>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fromPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="toPort" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ipProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element ref="{http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/}ipRanges"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fromPort",
        "toPort",
        "ipProtocol",
        "ipRanges"
    })
    public static class IpPermissionEgressItem {

        protected int fromPort;
        protected int toPort;
        @XmlElement(required = true)
        protected String ipProtocol;
        @XmlElement(required = true)
        protected IpRanges ipRanges;

        /**
         * Gets the value of the fromPort property.
         * 
         */
        public int getFromPort() {
            return fromPort;
        }

        /**
         * Sets the value of the fromPort property.
         * 
         */
        public void setFromPort(int value) {
            this.fromPort = value;
        }

        /**
         * Gets the value of the toPort property.
         * 
         */
        public int getToPort() {
            return toPort;
        }

        /**
         * Sets the value of the toPort property.
         * 
         */
        public void setToPort(int value) {
            this.toPort = value;
        }

        /**
         * Gets the value of the ipProtocol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIpProtocol() {
            return ipProtocol;
        }

        /**
         * Sets the value of the ipProtocol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIpProtocol(String value) {
            this.ipProtocol = value;
        }

        /**
         * Gets the value of the ipRanges property.
         * 
         * @return
         *     possible object is
         *     {@link IpRanges }
         *     
         */
        public IpRanges getIpRanges() {
            return ipRanges;
        }

        /**
         * Sets the value of the ipRanges property.
         * 
         * @param value
         *     allowed object is
         *     {@link IpRanges }
         *     
         */
        public void setIpRanges(IpRanges value) {
            this.ipRanges = value;
        }

    }

}
