//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 04:51:18 PM IST 
//


package xmlParser;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateRouteTableResponse }
     * 
     */
    public CreateRouteTableResponse createCreateRouteTableResponse() {
        return new CreateRouteTableResponse();
    }

    /**
     * Create an instance of {@link com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet }
     * 
     */
    public com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet createRouteSet() {
        return new com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet();
    }

    /**
     * Create an instance of {@link IpRanges }
     * 
     */
    public IpRanges createIpRanges() {
        return new IpRanges();
    }

    /**
     * Create an instance of {@link AssociationSet }
     * 
     */
    public AssociationSet createAssociationSet() {
        return new AssociationSet();
    }

    /**
     * Create an instance of {@link CreateSubnetResponse }
     * 
     */
    public CreateSubnetResponse createCreateSubnetResponse() {
        return new CreateSubnetResponse();
    }

    /**
     * Create an instance of {@link IpPermissionsEgress }
     * 
     */
    public IpPermissionsEgress createIpPermissionsEgress() {
        return new IpPermissionsEgress();
    }

    /**
     * Create an instance of {@link IpPermissions }
     * 
     */
    public IpPermissions createIpPermissions() {
        return new IpPermissions();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsResponse }
     * 
     */
    public DescribeSecurityGroupsResponse createDescribeSecurityGroupsResponse() {
        return new DescribeSecurityGroupsResponse();
    }

    /**
     * Create an instance of {@link RouteTableSet }
     * 
     */
    public RouteTableSet createRouteTableSet() {
        return new RouteTableSet();
    }

    /**
     * Create an instance of {@link CreateVpcResponse }
     * 
     */
    public CreateVpcResponse createCreateVpcResponse() {
        return new CreateVpcResponse();
    }

    /**
     * Create an instance of {@link DescribeVpcsResponse }
     * 
     */
    public DescribeVpcsResponse createDescribeVpcsResponse() {
        return new DescribeVpcsResponse();
    }

    /**
     * Create an instance of {@link DescribeSubnetsResponse }
     * 
     */
    public DescribeSubnetsResponse createDescribeSubnetsResponse() {
        return new DescribeSubnetsResponse();
    }

    /**
     * Create an instance of {@link DescribeSubnetsResponse.SubnetSet }
     * 
     */
    public DescribeSubnetsResponse.SubnetSet createDescribeSubnetsResponseSubnetSet() {
        return new DescribeSubnetsResponse.SubnetSet();
    }

    /**
     * Create an instance of {@link DescribeVpcsResponse.VpcSet }
     * 
     */
    public DescribeVpcsResponse.VpcSet createDescribeVpcsResponseVpcSet() {
        return new DescribeVpcsResponse.VpcSet();
    }

    /**
     * Create an instance of {@link RouteTableSet.RouteTableSetItem }
     * 
     */
    public RouteTableSet.RouteTableSetItem createRouteTableSetRouteTableSetItem() {
        return new RouteTableSet.RouteTableSetItem();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsResponse.SecurityGroupInfo }
     * 
     */
    public DescribeSecurityGroupsResponse.SecurityGroupInfo createDescribeSecurityGroupsResponseSecurityGroupInfo() {
        return new DescribeSecurityGroupsResponse.SecurityGroupInfo();
    }

    /**
     * Create an instance of {@link CreateRouteTableResponse.RouteTable }
     * 
     */
    public CreateRouteTableResponse.RouteTable createCreateRouteTableResponseRouteTable() {
        return new CreateRouteTableResponse.RouteTable();
    }

    /**
     * Create an instance of {@link CreateRouteTableResponse.RouteTable.RouteSet }
     * 
     */
    public CreateRouteTableResponse.RouteTable.RouteSet createCreateRouteTableResponseRouteTableRouteSet() {
        return new CreateRouteTableResponse.RouteTable.RouteSet();
    }

    /**
     * Create an instance of {@link DescribeAddressesResponse }
     * 
     */
    public DescribeAddressesResponse createDescribeAddressesResponse() {
        return new DescribeAddressesResponse();
    }

    /**
     * Create an instance of {@link com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet.RouteSetItem }
     * 
     */
    public com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet.RouteSetItem createRouteSetRouteSetItem() {
        return new com.jiocloudservices.ind_west_1.vpc.doc._2016_03_01.RouteSet.RouteSetItem();
    }

    /**
     * Create an instance of {@link AuthorizeSecurityGroupIngressResponse }
     * 
     */
    public AuthorizeSecurityGroupIngressResponse createAuthorizeSecurityGroupIngressResponse() {
        return new AuthorizeSecurityGroupIngressResponse();
    }

    /**
     * Create an instance of {@link CreateSecurityGroupResponse }
     * 
     */
    public CreateSecurityGroupResponse createCreateSecurityGroupResponse() {
        return new CreateSecurityGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteVpcResponse }
     * 
     */
    public DeleteVpcResponse createDeleteVpcResponse() {
        return new DeleteVpcResponse();
    }

    /**
     * Create an instance of {@link CreateRouteResponse }
     * 
     */
    public CreateRouteResponse createCreateRouteResponse() {
        return new CreateRouteResponse();
    }

    /**
     * Create an instance of {@link DeleteRouteResponse }
     * 
     */
    public DeleteRouteResponse createDeleteRouteResponse() {
        return new DeleteRouteResponse();
    }

    /**
     * Create an instance of {@link IpRanges.IpRangesItem }
     * 
     */
    public IpRanges.IpRangesItem createIpRangesIpRangesItem() {
        return new IpRanges.IpRangesItem();
    }

    /**
     * Create an instance of {@link AssociationSet.AssociationSetItem }
     * 
     */
    public AssociationSet.AssociationSetItem createAssociationSetAssociationSetItem() {
        return new AssociationSet.AssociationSetItem();
    }

    /**
     * Create an instance of {@link ReleaseAddressResponse }
     * 
     */
    public ReleaseAddressResponse createReleaseAddressResponse() {
        return new ReleaseAddressResponse();
    }

    /**
     * Create an instance of {@link DisassociateAddressResponse }
     * 
     */
    public DisassociateAddressResponse createDisassociateAddressResponse() {
        return new DisassociateAddressResponse();
    }

    /**
     * Create an instance of {@link CreateSubnetResponse.Subnet }
     * 
     */
    public CreateSubnetResponse.Subnet createCreateSubnetResponseSubnet() {
        return new CreateSubnetResponse.Subnet();
    }

    /**
     * Create an instance of {@link DeleteSecurityGroupResponse }
     * 
     */
    public DeleteSecurityGroupResponse createDeleteSecurityGroupResponse() {
        return new DeleteSecurityGroupResponse();
    }

    /**
     * Create an instance of {@link IpPermissionsEgress.IpPermissionEgressItem }
     * 
     */
    public IpPermissionsEgress.IpPermissionEgressItem createIpPermissionsEgressIpPermissionEgressItem() {
        return new IpPermissionsEgress.IpPermissionEgressItem();
    }

    /**
     * Create an instance of {@link DisassociateRouteTableResponse }
     * 
     */
    public DisassociateRouteTableResponse createDisassociateRouteTableResponse() {
        return new DisassociateRouteTableResponse();
    }

    /**
     * Create an instance of {@link RevokeSecurityGroupIngressResponse }
     * 
     */
    public RevokeSecurityGroupIngressResponse createRevokeSecurityGroupIngressResponse() {
        return new RevokeSecurityGroupIngressResponse();
    }

    /**
     * Create an instance of {@link DeleteSubnetResponse }
     * 
     */
    public DeleteSubnetResponse createDeleteSubnetResponse() {
        return new DeleteSubnetResponse();
    }

    /**
     * Create an instance of {@link AuthorizeSecurityGroupEgressResponse }
     * 
     */
    public AuthorizeSecurityGroupEgressResponse createAuthorizeSecurityGroupEgressResponse() {
        return new AuthorizeSecurityGroupEgressResponse();
    }

    /**
     * Create an instance of {@link AllocateAddressResponse }
     * 
     */
    public AllocateAddressResponse createAllocateAddressResponse() {
        return new AllocateAddressResponse();
    }

    /**
     * Create an instance of {@link IpPermissions.IpPermissionsItem }
     * 
     */
    public IpPermissions.IpPermissionsItem createIpPermissionsIpPermissionsItem() {
        return new IpPermissions.IpPermissionsItem();
    }

    /**
     * Create an instance of {@link RevokeSecurityGroupEgressResponse }
     * 
     */
    public RevokeSecurityGroupEgressResponse createRevokeSecurityGroupEgressResponse() {
        return new RevokeSecurityGroupEgressResponse();
    }

    /**
     * Create an instance of {@link AssociateAddressResponse }
     * 
     */
    public AssociateAddressResponse createAssociateAddressResponse() {
        return new AssociateAddressResponse();
    }

    /**
     * Create an instance of {@link DescribeRouteTablesResponse }
     * 
     */
    public DescribeRouteTablesResponse createDescribeRouteTablesResponse() {
        return new DescribeRouteTablesResponse();
    }

    /**
     * Create an instance of {@link CreateVpcResponse.Vpc }
     * 
     */
    public CreateVpcResponse.Vpc createCreateVpcResponseVpc() {
        return new CreateVpcResponse.Vpc();
    }

    /**
     * Create an instance of {@link AssociateRouteTableResponse }
     * 
     */
    public AssociateRouteTableResponse createAssociateRouteTableResponse() {
        return new AssociateRouteTableResponse();
    }

    /**
     * Create an instance of {@link DeleteRouteTableResponse }
     * 
     */
    public DeleteRouteTableResponse createDeleteRouteTableResponse() {
        return new DeleteRouteTableResponse();
    }

    /**
     * Create an instance of {@link DescribeSubnetsResponse.SubnetSet.Item }
     * 
     */
    public DescribeSubnetsResponse.SubnetSet.Item createDescribeSubnetsResponseSubnetSetItem() {
        return new DescribeSubnetsResponse.SubnetSet.Item();
    }

    /**
     * Create an instance of {@link DescribeVpcsResponse.VpcSet.Item }
     * 
     */
    public DescribeVpcsResponse.VpcSet.Item createDescribeVpcsResponseVpcSetItem() {
        return new DescribeVpcsResponse.VpcSet.Item();
    }

    /**
     * Create an instance of {@link RouteTableSet.RouteTableSetItem.RouteTable }
     * 
     */
    public RouteTableSet.RouteTableSetItem.RouteTable createRouteTableSetRouteTableSetItemRouteTable() {
        return new RouteTableSet.RouteTableSetItem.RouteTable();
    }

    /**
     * Create an instance of {@link DescribeSecurityGroupsResponse.SecurityGroupInfo.Item }
     * 
     */
    public DescribeSecurityGroupsResponse.SecurityGroupInfo.Item createDescribeSecurityGroupsResponseSecurityGroupInfoItem() {
        return new DescribeSecurityGroupsResponse.SecurityGroupInfo.Item();
    }

    /**
     * Create an instance of {@link CreateRouteTableResponse.RouteTable.RouteSet.Item }
     * 
     */
    public CreateRouteTableResponse.RouteTable.RouteSet.Item createCreateRouteTableResponseRouteTableRouteSetItem() {
        return new CreateRouteTableResponse.RouteTable.RouteSet.Item();
    }

}
