//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 04:51:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmlParser;
