//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.28 at 04:51:18 PM IST 
//


package xmlParser;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="routeTable">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/}routeSet"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="routeTableId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vpcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "routeTableSet")
public class RouteTableSet {

    @XmlElement(nillable = true)
    protected List<RouteTableSet.RouteTableSetItem> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteTableSet.RouteTableSetItem }
     * 
     * 
     */
    public List<RouteTableSet.RouteTableSetItem> getItem() {
        if (item == null) {
            item = new ArrayList<RouteTableSet.RouteTableSetItem>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="routeTable">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/}routeSet"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="routeTableId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vpcId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeTable",
        "routeTableId",
        "vpcId"
    })
    public static class RouteTableSetItem {

        @XmlElement(required = true)
        protected RouteTableSet.RouteTableSetItem.RouteTable routeTable;
        @XmlElement(required = true)
        protected String routeTableId;
        @XmlElement(required = true)
        protected String vpcId;

        /**
         * Gets the value of the routeTable property.
         * 
         * @return
         *     possible object is
         *     {@link RouteTableSet.RouteTableSetItem.RouteTable }
         *     
         */
        public RouteTableSet.RouteTableSetItem.RouteTable getRouteTable() {
            return routeTable;
        }

        /**
         * Sets the value of the routeTable property.
         * 
         * @param value
         *     allowed object is
         *     {@link RouteTableSet.RouteTableSetItem.RouteTable }
         *     
         */
        public void setRouteTable(RouteTableSet.RouteTableSetItem.RouteTable value) {
            this.routeTable = value;
        }

        /**
         * Gets the value of the routeTableId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRouteTableId() {
            return routeTableId;
        }

        /**
         * Sets the value of the routeTableId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRouteTableId(String value) {
            this.routeTableId = value;
        }

        /**
         * Gets the value of the vpcId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVpcId() {
            return vpcId;
        }

        /**
         * Sets the value of the vpcId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVpcId(String value) {
            this.vpcId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://vpc.ind-west-1.jiocloudservices.com/doc/2016-03-01/}routeSet"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "routeSet"
        })
        public static class RouteTable {

            @XmlElement(required = true)
            protected RouteSet routeSet;

            /**
             * Gets the value of the routeSet property.
             * 
             * @return
             *     possible object is
             *     {@link RouteSet }
             *     
             */
            public RouteSet getRouteSet() {
                return routeSet;
            }

            /**
             * Sets the value of the routeSet property.
             * 
             * @param value
             *     allowed object is
             *     {@link RouteSet }
             *     
             */
            public void setRouteSet(RouteSet value) {
                this.routeSet = value;
            }

        }

    }

}
